export const countryList = [
    "Anguilla",
    "Antigua and Barbuda",
    "Aruba",
    "Bahamas",
    "Barbados",
    "British Virgin Islands",
    "Cayman Islands",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "Grenada",
    "Guadeloupe",
    "Haiti",
    "Jamaica",
    "Martinique",
    "Montserrat",
    "Netherlands Antilles",
    "Puerto Rico",
    "Saint Barthelemy",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "St Martin",
    "Saint Vincent and the Grenadines",
    "Trinidad and Tobago",
    "Turks & Caicos Islands",
    "US Virgin Islands",
    "Venezuela",
    "Guyana",
    "Belize",
    "French Guiana",
    "Suriname",
    "Panama"
  ];